/** Curated emoji set for folder appearance (searchable labels). */

export type FolderEmojiEntry = {
  emoji: string
  labels: string
}

export const FOLDER_EMOJIS: FolderEmojiEntry[] = [
  { emoji: '📁', labels: 'folder file' },
  { emoji: '📂', labels: 'folder open' },
  { emoji: '🗂️', labels: 'dividers files' },
  { emoji: '📌', labels: 'pin' },
  { emoji: '📍', labels: 'location pin' },
  { emoji: '⭐', labels: 'star favorite' },
  { emoji: '🔥', labels: 'fire hot' },
  { emoji: '💡', labels: 'idea lightbulb' },
  { emoji: '🚀', labels: 'rocket launch' },
  { emoji: '🎯', labels: 'target goal' },
  { emoji: '✅', labels: 'check done' },
  { emoji: '📝', labels: 'notes memo' },
  { emoji: '📒', labels: 'notebook' },
  { emoji: '📕', labels: 'book red' },
  { emoji: '📗', labels: 'book green' },
  { emoji: '📘', labels: 'book blue' },
  { emoji: '📙', labels: 'book orange' },
  { emoji: '📚', labels: 'books' },
  { emoji: '💼', labels: 'briefcase work' },
  { emoji: '🏢', labels: 'building office' },
  { emoji: '🏠', labels: 'home house' },
  { emoji: '👥', labels: 'people team' },
  { emoji: '🤝', labels: 'handshake deal' },
  { emoji: '💬', labels: 'chat message' },
  { emoji: '📞', labels: 'phone call' },
  { emoji: '📧', labels: 'email mail' },
  { emoji: '📅', labels: 'calendar date' },
  { emoji: '⏰', labels: 'alarm time' },
  { emoji: '🎙️', labels: 'mic microphone' },
  { emoji: '🎧', labels: 'headphones audio' },
  { emoji: '🎬', labels: 'film clapper' },
  { emoji: '📹', labels: 'video camera' },
  { emoji: '🖥️', labels: 'desktop computer' },
  { emoji: '💻', labels: 'laptop' },
  { emoji: '📱', labels: 'phone mobile' },
  { emoji: '🔑', labels: 'key' },
  { emoji: '🔒', labels: 'lock private' },
  { emoji: '🛡️', labels: 'shield security' },
  { emoji: '💰', labels: 'money bag' },
  { emoji: '📊', labels: 'chart bars' },
  { emoji: '📈', labels: 'chart up' },
  { emoji: '🧾', labels: 'receipt invoice' },
  { emoji: '🏷️', labels: 'tag label' },
  { emoji: '📎', labels: 'paperclip attach' },
  { emoji: '🔗', labels: 'link' },
  { emoji: '🧠', labels: 'brain think' },
  { emoji: '❤️', labels: 'heart love' },
  { emoji: '🧡', labels: 'heart orange' },
  { emoji: '💛', labels: 'heart yellow' },
  { emoji: '💚', labels: 'heart green' },
  { emoji: '💙', labels: 'heart blue' },
  { emoji: '💜', labels: 'heart purple' },
  { emoji: '⚡', labels: 'lightning energy' },
  { emoji: '✨', labels: 'sparkles' },
  { emoji: '🌈', labels: 'rainbow' },
  { emoji: '☕', labels: 'coffee' },
  { emoji: '🍕', labels: 'pizza food' },
  { emoji: '🎉', labels: 'party celebrate' },
  { emoji: '🏆', labels: 'trophy win' },
  { emoji: '🎁', labels: 'gift present' },
  { emoji: '🌱', labels: 'plant growth' },
  { emoji: '🌍', labels: 'earth world' },
  { emoji: '✈️', labels: 'plane travel' },
  { emoji: '🚗', labels: 'car' },
  { emoji: '🛠️', labels: 'tools wrench' },
  { emoji: '⚙️', labels: 'gear settings' },
  { emoji: '🧪', labels: 'lab science' },
  { emoji: '🎨', labels: 'art palette' },
  { emoji: '📷', labels: 'camera photo' },
  { emoji: '🔔', labels: 'bell alert' },
  { emoji: '📣', labels: 'megaphone announce' },
  { emoji: '🧭', labels: 'compass' },
  { emoji: '🗺️', labels: 'map' },
  { emoji: '💤', labels: 'sleep zzz' },
  { emoji: '🐶', labels: 'dog' },
  { emoji: '🐱', labels: 'cat' },
  { emoji: '🦊', labels: 'fox' },
  { emoji: '🐻', labels: 'bear' },
]

export function filterFolderEmojis(query: string): FolderEmojiEntry[] {
  const q = query.trim().toLowerCase()
  if (!q) return FOLDER_EMOJIS
  return FOLDER_EMOJIS.filter(
    (entry) => entry.emoji.includes(q) || entry.labels.includes(q),
  )
}
