import { getOutputLanguage } from './audioPreferences'
import { languageLabel } from './languages'
import { proxyMeetingChat } from './proxyClient'
import type { StoredMeeting } from './meetingStore'
import { isAutoGeneratedMeetingTitle, updateMeeting } from './meetingStore'
import { resolveSpeakerDisplay } from './transcriptUtils'
import {
  extractActionItems,
  extractOverviewSummary,
} from '../shared/parseEnhancedNotes'

function transcriptLines(meeting: StoredMeeting): string[] {
  const labels = meeting.speakerLabels ?? {}
  return meeting.transcript.map(
    (entry) => `${resolveSpeakerDisplay(entry.speaker, labels)}: ${entry.text}`,
  )
}

function formatMeetingMeta(meeting: StoredMeeting): string {
  const parts: string[] = [`Meeting title: ${meeting.title}`]
  if (meeting.startedAt) {
    parts.push(`Date: ${new Date(meeting.startedAt).toISOString()}`)
  }
  if (meeting.startedAt && meeting.endedAt && meeting.endedAt > meeting.startedAt) {
    const minutes = Math.max(1, Math.round((meeting.endedAt - meeting.startedAt) / 60_000))
    parts.push(`Duration: ~${minutes} min`)
  }
  const speakers = Object.values(meeting.speakerLabels ?? {}).filter(Boolean)
  if (speakers.length > 0) {
    parts.push(`Speakers: ${speakers.join(', ')}`)
  }
  return parts.join('\n')
}

function buildEnhancePrompt(meeting: StoredMeeting): string {
  const notes = meeting.userNotes.trim() || '(no notes taken during the meeting)'
  const outputLanguage = getOutputLanguage()
  const languageNote =
    outputLanguage !== 'en'
      ? `\n\nKeep structural section headers in English (especially "# Next Steps"), but write all other content in ${languageLabel(outputLanguage)}.`
      : ''

  return [
    'Write a polished Enhanced meeting note from the transcript and user scratchpad below.',
    '',
    'Requirements:',
    '- Invent topical # Section headings from what was discussed (like a Granola Enhanced note) — do not force a fixed Overview / Key points / Decisions shell when richer topics fit.',
    '- Use nested markdown bullets (- and indented sub-bullets) with concrete specifics: names, numbers, dates, orgs, commitments.',
    '- Prefer the user scratchpad as the skeleton when present; fill gaps from the transcript. If the transcript is sparse, lean on user notes.',
    '- Optional insight callouts as markdown blockquotes (> ...) when advice or framing was given.',
    '- End with exactly: # Next Steps',
    '- Under Next Steps, list actionable bullets; bold the core action phrase with **...**.',
    '- Dense, specific, and scannable — not vague, padded, or a raw transcript dump.',
    languageNote,
    '',
    formatMeetingMeta(meeting),
    '',
    'User notes during the meeting (scratchpad):',
    notes,
  ].join('\n')
}

function mergeCompletedActionItems(
  previousCompleted: string[] | undefined,
  nextItems: string[],
): string[] {
  if (!previousCompleted?.length || nextItems.length === 0) return []
  const nextSet = new Set(nextItems.map((item) => item.toLowerCase()))
  return previousCompleted.filter((item) => nextSet.has(item.toLowerCase()))
}

function sanitizeAutoTitle(raw: string): string | undefined {
  let title = raw.trim().split('\n')[0]?.trim() ?? ''
  title = title
    .replace(/^["'`“”]+|["'`“”]+$/g, '')
    .replace(/^(title|meeting title)\s*[:\-–]\s*/i, '')
    .replace(/\.$/, '')
    .trim()
  if (title.length < 3 || title.length > 72) return undefined
  if (/^(untitled|meeting|notes|new meeting)$/i.test(title)) return undefined
  return title
}

async function proposeMeetingTitle(meeting: StoredMeeting): Promise<string | undefined> {
  if (!isAutoGeneratedMeetingTitle(meeting)) return undefined

  const lines = transcriptLines(meeting)
  const notes = meeting.userNotes.trim().slice(0, 1_500)
  const excerpt = lines.slice(0, 50).join('\n')
  if (!excerpt && !notes) return undefined

  const outputLanguage = getOutputLanguage()
  const languageNote =
    outputLanguage !== 'en'
      ? ` Write the title in ${languageLabel(outputLanguage)}.`
      : ''

  const result = await proxyMeetingChat({
    message: [
      'Create a short meeting note title (3–8 words) that captures what was discussed.',
      `Reply with ONLY the title text — no quotes, no prefix, no trailing period.${languageNote}`,
      '',
      formatMeetingMeta(meeting),
      notes ? `\nUser notes:\n${notes}` : '',
      '',
      'Transcript excerpt:',
      excerpt || '(empty)',
    ]
      .filter(Boolean)
      .join('\n'),
    transcriptLines: lines.slice(0, 60),
    purpose: 'enhance_notes',
  })

  if ('error' in result) return undefined
  return sanitizeAutoTitle(result.reply)
}

export async function enhanceMeetingNotes(meetingId: string): Promise<StoredMeeting | null> {
  const meeting = updateMeeting(meetingId, { status: 'processing', enhanceError: undefined })
  if (!meeting) return null

  const result = await proxyMeetingChat({
    message: buildEnhancePrompt(meeting),
    transcriptLines: transcriptLines(meeting),
    purpose: 'enhance_notes',
  })

  if ('error' in result) {
    const enhanceError =
      result.error === 'network_error'
        ? 'network_error'
        : result.error === 'auth_expired' || result.error === 'not_authenticated'
          ? 'Connect your account to generate your AI summary.'
          : result.error
    return updateMeeting(meetingId, {
      status: 'error',
      enhanceError,
    })
  }

  const { summary, actionItems, body } = parseEnhancedReply(result.reply)
  const completedActionItems = mergeCompletedActionItems(
    meeting.completedActionItems,
    actionItems ?? [],
  )
  const autoTitle = await proposeMeetingTitle(meeting)
  return updateMeeting(meetingId, {
    status: 'ready',
    enhancedNotes: body,
    summary,
    actionItems,
    completedActionItems,
    enhanceError: undefined,
    ...(autoTitle ? { title: autoTitle } : {}),
  })
}

function parseEnhancedReply(reply: string): {
  summary?: string
  actionItems?: string[]
  body: string
} {
  const body = reply.trim()
  const actionItems = extractActionItems(body)
  const summary = extractOverviewSummary(body)
  return {
    summary,
    actionItems: actionItems.length > 0 ? actionItems : undefined,
    body,
  }
}
