/// <reference types="vite/client" />

type ElectronInvoke =
  | 'ping'
  | 'auth:connection-status'
  | 'auth:open-connect'
  | 'auth:open-sign-in'
  | 'auth:open-dashboard'
  | 'auth:open-legal'
  | 'calendar:status'
  | 'calendar:events'
  | 'calendar:open-connect'
  | 'meetings:list'
  | 'meetings:get'
  | 'meetings:create'
  | 'meetings:update'
  | 'meetings:delete'
  | 'meetings:enhance'
  | 'audio:start'
  | 'audio:pause'
  | 'audio:resume'
  | 'audio:stop'
  | 'audio:status'
  | 'audio:chunk'
  | 'audio:session-transcript'
  | 'audio:get-preferences'
  | 'audio:set-preferences'
  | 'audio:list-microphones'
  | 'onboarding:get'
  | 'onboarding:save'
  | 'onboarding:complete'
  | 'permissions:status'
  | 'permissions:request-microphone'
  | 'permissions:open-microphone-settings'
  | 'permissions:open-system-audio-settings'
  | 'widget:show'
  | 'widget:hide'
  | 'widget:close'
  | 'widget:focus-main'
  | 'widget:open-meeting'
  | 'widget:stop-recording'
  | 'widget:pause-recording'
  | 'widget:resume-recording'
  | 'widget:expand'
  | 'widget:collapse'
  | 'widget:set-panel'
  | 'widget:get-session'
  | 'widget:update-notes'
  | 'widget:rename-speaker'
  | 'error:report'
  | 'enhance:retry-pending'

type ElectronEvent =
  | 'transcript:update'
  | 'transcription:activity'
  | 'auth:connected'
  | 'meetings:changed'
  | 'meetings:enhanced'
  | 'meetings:needs-connect'
  | 'audio:prefs-changed'
  | 'widget:state'
  | 'widget:navigate-meeting'
  | 'audio:stopped'
  | 'audio:session-paused'
  | 'audio:session-resumed'

interface Window {
  electronAPI: {
    send(channel: string, data: unknown): void
    on(channel: ElectronEvent, callback: (...args: unknown[]) => void): () => void
    invoke(channel: ElectronInvoke, data?: unknown): Promise<unknown>
  }
}
